### ISSUE TITLE
pretrain问题

### ISSUE THREAD

**Issue by zhongqiu1245** [pengzhiliang/Conformer#12]
作者您好
非常感谢您的工作！
请问您的mmdet的config可以正确的加载您的imagenet模型作为pretrain吗？
谢谢！

**Comment by pengzhiliang** [comment]
谢谢！
只要参数设置没问题就可以。

**Comment by zhongqiu1245** [comment]
谢谢您的回复
请问您会release语义分割的代码吗（with conformer），比如mmseg的？
这么优秀的backbone在语义分割的效果一定十分惊艳

**Comment by pengzhiliang** [comment]
谢谢你的美言。
但是我不会分割呀。

**Comment by myself0816** [comment]
我把它用在分割上了，但是不知道咋回事，效果很差，我又找不出原因来

**Comment by 2252033991** [comment]
> 我把它用在分割上了，但是不知道咋回事，效果很差，我又找不出原因来
请问你后来有继续研究吗，我用到目标检测上，效果也很差
