### ISSUE TITLE
About feature analysis

### ISSUE THREAD

**Issue by FreezerBreath** [pengzhiliang/Conformer#15]
你好，我想问一下你在论文中提到的特征分析中，是用什么方法将注意力绘制到原图上的？就是在Attention操作之后，得到的特征图是多通道的，你是用什么方法将其合并的？

**Comment by pengzhiliang** [comment]
你好，attention map最后是只有一个通道的，实现方式见：https://github.com/pengzhiliang/Conformer/issues/10#issuecomment-903207037

**Comment by FreezerBreath** [comment]
好的  谢谢
