### ISSUE TITLE
why does model not load state dict when do inference?

### ISSUE THREAD

**Issue by HIT-lcccc** [pengzhiliang/Conformer#19]
When just do inference using the model, I found that the model don't do `load_state_dict` after `torch.load`
The related code is from line 301 to line 322 in './Conformer-main/main.py'

**Comment by pengzhiliang** [comment]
sorry for the later reply.

I tryed:
```python
import torch
import models

model = models.Conformer_small_patch16().cuda()
model.load_state_dict(torch.load('./Conformer_small_patch16.pth'), strict=True)
```
But no problem was found.

**Comment by HIT-lcccc** [comment]
Thanks for your reply. I mean that when I use the command 
```
CUDA_VISIBLE_DEVICES=0, python main.py  --model Conformer_tiny_patch16 --eval --batch-size 64 \
                --input-size 224 \
                --data-set IMNET \
                --num_workers 4 \
                --data-path ../ImageNet_ILSVRC2012/ \
                --epochs 100 \
                --resume ../Conformer_tiny_patch16.pth
``` 
in run.sh, the inference model seems not load the dict whose path is shown in "--resume".

**Comment by pengzhiliang** [comment]
Hello, I run the commands you mentioned and get the results:
![image](https://user-images.githubusercontent.com/26346329/141466496-00383f8e-037b-4ce1-89f9-8cedc766b961.png)

Maybe you need to check the path of model weight?
Or the `--resume` path doesn't pass to the `args`.

**Comment by HIT-lcccc** [comment]
Thanks for your reply again. I will check the code and my running environment carefully.

**Comment by pengzhiliang** [comment]
OK, thank u~
