### ISSUE TITLE
conformer_small_patch32.pth

### ISSUE THREAD

**Issue by JarvisKevin** [pengzhiliang/Conformer#27]
Nice work! And I have some questions here.
The "small" pretrained model posted on home page is conformer_small_patch16.pth. And I haven't found the patch32 one which is the pretrained model in your faster RCNN's config. May I ask this checkpoint file, please? And Can you provide the configuration file of Base and Large model? Thank you very much!

**Comment by pengzhiliang** [comment]
hello, the model link  is [here](https://drive.google.com/file/d/1UrvRg2hnXsie_z_y39Xavdts4qfrwZ1E/view?usp=sharing)

**Comment by JarvisKevin** [comment]
So kind of you, thankyou.

**Comment by JarvisKevin** [comment]
So kind of you, thankyou.

**Comment by 2252033991** [comment]
> 好心的你，谢谢。

Does your reproduction code have a good effect?
