### ISSUE TITLE
VOC格式的数据集可以训练吗

### ISSUE THREAD

**Issue by ZZM11** [pengzhiliang/Conformer#3]
请问这个有办法训练voc的数据集吗？效果怎么样？

**Comment by pengzhiliang** [comment]
你好，VOC数据集是指检测还是多标签分类？

**Comment by pengzhiliang** [comment]
是可以的，只需要把conformer基网放到几个检测框架中去就行，后期我们也将开源mmdetection的代码

**Comment by pengzhiliang** [comment]
你好~ 检测代码可参考：https://github.com/pengzhiliang/Conformer/tree/main/mmdetection
