### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by DrChenziyan** [pengzhiliang/Conformer#9]
1. Could you interpret the `last_fusion` in `ConvTransBlock`?  I did not find a specific explanation in your paper.
2. In `ConvBlock`, could you explain what is `x_t` in the forward function?

**Comment by pengzhiliang** [comment]
Hi~:

A1. The `last_fusion ` is still a `conv` block.
A2. We need to fuse the features `x` in `ConvBlock` with the feature `x_t` from `TransBlock`.
